### ISSUE TITLE
Infinite load of a instance page

### ISSUE THREAD

**Issue by pbuyle** [StudioQi/jeto#52]
When visiting an instance page, the loader is displayed for ever without any other kind of feedback.

If I open the the JavaScript console, I can that a request to `/api/instance/{id}` failed with a 502 error. But the UI does not provide any feedback. Please add error handling to at least let the user known when something went wrong without requiring her to work with an open JavaScript console.

**Comment by pbuyle** [comment]
This is done by passing a second callvack to the `Isntances.get()` call at https://github.com/StudioQi/jeto/blob/master/jeto/static/js/controllers/instance.js#L6

**Comment by abondis** [comment]
it happens when vagrant returns an error, it seems like the worker has issues parsing it or catching the error

**Comment by pbuyle** [comment]
The problem is that the UI does not handle error during the request. Even if the error was properly reported to the client, it would not be displayed tp the user and the loading bar will still be displayed for ever.

**Comment by abondis** [comment]
https://github.com/StudioQi/jeto/issues/49

**Comment by PierrePaul** [comment]
https://github.com/StudioQi/jeto/commit/48a672847fcc98fce625f37faf62f3b53bd8e32b
