### ISSUE TITLE
Permissions not listed in admin/teams

### ISSUE THREAD

**Issue by abondis** [StudioQi/jeto#53]
we can only see 'view instances on host' when selecting the Hosts permission.

**Comment by PierrePaul** [comment]
Need more details, I'm not able to reproduce. Maybe the fix is already fixed. I remember hacking and redoing either this template or the user template from the admin.

**Comment by abondis** [comment]
I'll check when I upgrade, right now I see thist :
![2015-09-10-141210_788x462_scrot](https://cloud.githubusercontent.com/assets/262635/9796805/fd7b55d2-57c5-11e5-9abe-b9d97a784a17.png)
