### ISSUE TITLE
domains : ssl empty

### ISSUE THREAD

**Issue by abondis** [StudioQi/jeto#75]
when modifying a domain, if it had an SSL certificate, it is emptied and saving will save a domain without an SSL.

**Comment by PierrePaul** [comment]
Manually fetching the keys before showing up the Dialog form seems to work, but I need to disable the automatic $watch on the domainInfo if I do this. And if I disable the $watch, it means we dont get keys when we want to create a new domain. Will try to refactor the create function to manually get the keys or refactor the whole controller to have seperate variables at least for each action.
