### ISSUE TITLE
Domain don't save changes sometimes

### ISSUE THREAD

**Issue by Calystod** [StudioQi/jeto#77]
Sometimes, after changing in a domain and click on save, my changes aren't take and I recover the old datas. I must repeat the operation a couple of time before they are really saved.

I don't know if errors happen, I have no message or strange comportment in frontend.

**Comment by PierrePaul** [comment]
Im guessing the data is updated on the backend but takes time to save. The UI should update data in the callback of the save instead of doing this manually.
