### ISSUE TITLE
Support execution of scripts in an instance

### ISSUE THREAD

**Issue by pbuyle** [StudioQi/jeto#9]
Add support for executing pre-defined, named scripts inside an instance, fron the UI. This is not to be used for provisioning (ie. provisioning of he instance should be done using Vagrant provisioning), but rather for scripts that an administrator may want to run manually on a machine. The script could be run using the `vagrant ssh -c  "$SCRIPT"`.

For instance, being able to run the following kind of scripts from the UI would be nice:
 - Extraction of a DB dump
 - Execution of a cleanup method

Scripts could be specified per-instance. Either from the UI, or using a JSON file (see #8). With the later being able to have something like the following in a JSON would be great:
```
{
  ...
  "scripts": {
    "database-dump": "/vagrant/src/scripts/dbdump.sh"
    "database-cleanup": "cd /vagrant/src/cleanup && npm start"
  }
  ...
}
```

**Comment by PierrePaul** [comment]
Completed, tagged in the 0.2.1.
Thanks!

**Comment by PierrePaul** [comment]
Basic explanation : https://github.com/StudioQi/jeto/wiki/jeto.json-file

**Comment by pbuyle** [comment]
`command` is simply a shell command directly executed in the VM/Container using the default Vagrant user?

**Comment by PierrePaul** [comment]
Yes, like proposed, using vagrant ssh <machineName> -c "command"
